import { StyleSheet, Dimensions } from "react-native";

const SCREEN_WIDTH = Dimensions.get("window").width;
const SCREEN_HEIGHT = Dimensions.get("window").height;

const colors = {
    white: "#ffffff",
    black: "#000000",
    grey_0: "#d5d5d5",
    grey_1: "#a6a6a6",
    red: "#ff3300",
    blue: "#0080ff",
    skyBlue: "#e6f7ff",
    navy: "#004080",
    orange: "#ffd11a",
    grass: "#80cd32",
    blue_1: "#80c1ff",
};

const style = StyleSheet.create({
    colorList: {
        white: "#ffffff",
        black: "#000000",
        grey_0: "#d5d5d5",
        grey_1: "#a6a6a6",
        red: "#ff3300",
        blue: "#0080ff",
        skyBlue: "#e6f7ff",
        navy: "#004080",
        grass: "#80cd32",
        orange: "#ffd11a",
        blue_1: "#80c1ff",
    },
    days: {
        flex: 0.05,
        backgroundColor: colors.skyBlue,
        alignItems: "center",
        justifyContent: "space-around",
        width: SCREEN_WIDTH - 40,
        flexDirection: "row",
        // borderColor: colors.navy,
        // borderWidth: 1,
    },
    dateContainer: {
        //backgroundColor: 'tomato',
        flex: 1,
        //borderWidth: 0.5,
        borderColor: colors.navy,
        borderTopWidth: 0.5,
        alignItems: "stretch",
    },
    weekContainer: {
        //backgroundColor: colors.orange,
        // borderWidth: 4,
        // borderColor: 'blue',
        flex: 1,
        alignItems: "stretch",
        width: SCREEN_WIDTH - 40,
        flexDirection: "row",
    },
    monthContainer: {
        flex: 0.95,
        backgroundColor: colors.skyBlue,
        alignItems: "center",
        justifyContent: "center",
        width: SCREEN_WIDTH - 40,
        //borderRadius: 10,
        // borderColor: colors.navy,
        // borderWidth: 1,
    },
    currentMonthDateContainer: {
        flex: 1,
        backgroundColor: colors.white,
        alignItems: "center",
        justifyContent: "space-around",
        width: SCREEN_WIDTH - 40,
        flexDirection: "row",
        borderColor: "green",
        borderWidth: 5,
    },
    notCurrentMonthDateContainer: {
        flex: 1,
        backgroundColor: colors.grey_0,
        alignItems: "center",
        justifyContent: "space-around",
        width: SCREEN_WIDTH - 40,
        flexDirection: "row",
        borderColor: "green",
        borderWidth: 5,
    },
    spinnerContainer: {
        position: "absolute",
        zIndex: 2,
        opacity: 0.3,
        width: SCREEN_WIDTH,
        height: SCREEN_HEIGHT,
        justifyContent: "center",
        backgroundColor: colors.black,
    },
    theme: {
        backgroundColor: colors.skyBlue,
    },
    size: {
        width_: SCREEN_WIDTH,
        height_: SCREEN_HEIGHT,
    },
    btnTitle: {
        height: 30,
        lineHeight: 30,
        fontSize: 16,
        color: colors.white,
    },
    container: {
        flex: 1,
        backgroundColor: colors.skyBlue,
        justifyContent: "center",
        // alignItems: 'center',
    },
    btnContainer: {
        backgroundColor: colors.navy,
        alignItems: "center",
        borderRadius: 4,
        width: SCREEN_WIDTH - 40,
        padding: 10,
        marginHorizontal: 20,
    },
    navigationContainer: {
        flex: 1,
        backgroundColor: "#ff00ff",
        justifyContent: "center",
        alignItems: "center",
    },
    text: {
        color: "#003399",
        fontSize: 60,
        alignItems: "center",
    },
    btn: {
        backgroundColor: "#000000",
        color: "#ffffff",
        paddingHorizontal: 50,
        paddingVertical: 50,
        fontSize: 40,
    },
    input: {
        height: 40,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        backgroundColor: "white",
        width: "80%",
    },
    inputView: {
        flexDirection: "column",
        width: SCREEN_WIDTH - 40,
        marginVertical: 10,
    },
    label: {
        fontSize: 14,
        fontWeight: "600",
        marginBottom: 6,
        color: colors.black,
    },
    itemContainer: {
        flexDirection: "row",
        alignItems: "center",
        borderBottomWidth: 1,
        borderColor: colors.grey_0,
        paddingVertical: 15,
        paddingHorizontal: 20,
    },
    textInput: {
        width: SCREEN_WIDTH - 40,
        placeholderTextColor: colors.grey_1,
        backgroundColor: colors.white,
        color: colors.black,
        paddingVertical: 20,
        paddingHorizontal: 10,
        fontSize: 16,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: colors.navy,
        borderRadius: 4,
    },
    view: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "lightgrey",
    },
    btnView: {
        flex: 0.5,
        alignItems: "center",
        justifyContent: "space-around",
        backgroundColor: "green",
        flexDirection: "row",
        marginTop: 40,
        width: "90%",
    },
    cameraBtn: {
        backgroundColor: colors.grey_1,
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
    },
    firstView: {
        flex: 1,
        backgroundColor: "yellow",
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    secondView: {
        flexDirection: "row",
        flex: 1,
        backgroundColor: "purple",
        width: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    thirdView: {
        flex: 1,
        backgroundColor: "green",
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    matchingView: {
        flex: 1,
        backgroundColor: "purple",
        width: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    calendarView: {
        flex: 3,
        backgroundColor: "purple",
        width: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    classView: {
        flex: 1.3,
        backgroundColor: "#32f39f",
        width: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    classListView: {
        flex: 3,
        backgroundColor: "pink",
        width: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    newClassView: {
        flex: 1,
        backgroundColor: "green",
        width: "100%",
        justifyContent: "space-evenly",
        alignItems: "center",
    },
    loginForm: {
        flex: 0.5,
        backgroundColor: "green",
        width: "70%",
        alignItems: "center",
        marginTop: -80,
    },
});

export default style;
